language: python

# 3.6 is listed first so it gets used for the later build stages
python:
  - "3.6"
  - "3.7-dev"

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

script:
  - pip install -U pytest
  - pytest

cache:
    directories:
      - $HOME/.cache/pip

jobs:
  include:
    - stage: release tagged version
      if: tag IS present
      language: python
      python: 3.6
      script:
        - pip install -U pip wheel
        - npm install -g now
        - pip install https://github.com/simonw/datasette/archive/master.zip
        - curl --silent -o 24ways-fts4.db https://24ways-fts4-db.now.sh/
        - datasette publish now 24ways-fts4.db --token=$NOW_TOKEN --alias=datasette-sqlite-fts4.datasette.io --name=datasette-sqlite-fts4 --install https://github.com/simonw/sqlite-fts4/archive/$TRAVIS_TAG.zip --install=datasette-sqlite-fts4 --install=datasette-json-html
      deploy:
        - provider: pypi
          user: simonw
          distributions: bdist_wheel
          password: ${PYPI_PASSWORD}
          on:
            branch: master
            tags: true
            repo: simonw/sqlite-fts4
